var colour = "red";
console.log("Is colour=red , I predict true ");
console.log(colour == "red");
var age = 30;
console.log(" IS age<30, I predict false");
console.log(age < 30);
var bike = "honda";
console.log("Is bike=honda , I predict true ");
console.log(bike == "honda");
var city = "karachi";
console.log("Is city=karachi, I predict true ");
console.log(city == "karachi");
var grade = "A";
console.log("Is grade!=A, I predict false ");
console.log(grade != "A");
var favouritenum = "46";
console.log("Is favouritenum >=46, I predict true ");
console.log(favouritenum >= "46");
