var x = 10;
console.log(" IS x!=10, I predict false");
console.log(x != 10);
var i = true;
var j = false;
console.log("Is i && j? I predict false.");
console.log(i && j);
var k = true;
var l = false;
console.log("Is k || l? I predict true.");
console.log(k || l);
var fruits = ['apple', 'banana', 'orange'];
console.log("Array item check;" + fruits == 'apple');
